"use client";
import { useEffect,useState } from "react";
import { deleteAttempt,listAttempts } from "./practice-repository";
import { realAttempts,patterns,compareAttempts } from "./practice-patterns";
import { seconds,STAR_KEYS,type Attempt } from "./practice-types";
import InterviewReport from "./interview-report";

export default function PracticeReports({refresh}:{refresh:number}){
  const [attempts,setAttempts]=useState<Attempt[]>([]),[loaded,setLoaded]=useState(""),[error,setError]=useState("");
  const [selected,setSelected]=useState(""),[compare,setCompare]=useState(""),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false);
  const [next,setNext]=useState<number|null>(null),[total,setTotal]=useState(0);
  const loading=loaded!==`${refresh}:${retry}`;
  useEffect(()=>{
    let active=true;
    listAttempts().then(data=>{if(active){setError("");setAttempts(data.attempts);setTotal(data.total);setNext(data.next);setSelected(data.attempts[0]?.id||"");setCompare("");}}).catch(err=>{if(active)setError(err.message);}).finally(()=>{if(active)setLoaded(`${refresh}:${retry}`);});
    return ()=>{active=false;};
  },[refresh,retry]);
  async function more(){setBusy(true);setError("");try{const data=await listAttempts(next!);setAttempts(prev=>[...prev,...data.attempts.filter(a=>!prev.some(p=>p.id===a.id))]);setNext(data.next);setTotal(data.total);}catch(err){setError(err instanceof Error?err.message:"Could not load more reports.");}finally{setBusy(false);}}
  async function remove(attempt:Attempt){if(!window.confirm("Permanently delete this attempt, transcript, and report?"))return;setBusy(true);setError("");try{await deleteAttempt(attempt.id);setAttempts(prev=>prev.filter(a=>a.id!==attempt.id));setSelected("");setCompare("");setTotal(n=>n-1);}catch(err){setError(err instanceof Error?err.message:"Delete failed.");}finally{setBusy(false);}}
  const real=realAttempts(attempts),current=attempts.find(a=>a.id===selected),previous=attempts.find(a=>a.id===compare);
  const avg=(field:"wpm"|"filler_rate")=>real.length?(real.reduce((sum,a)=>sum+a.metrics[field],0)/real.length).toFixed(1):"—";
  const groups=[...new Set(attempts.map(a=>a.question_id))].map(id=>attempts.filter(a=>a.question_id===id));
  const insights=patterns(attempts);
  const points=real.slice(-12);
  function chart(key:"Overall"|"wpm"|"filler_rate",label:string){
    const values=points.map(a=>key==="Overall"?a.analysis.scores.Overall:a.metrics[key]);const max=Math.max(1,...values);
    return <figure className="report-chart"><figcaption>{label} · latest {points.length} real attempts</figcaption><svg viewBox="0 0 360 120" role="img" aria-label={`${label}: ${values.join(', ')} in chronological order`}><line x1="20" y1="95" x2="340" y2="95" stroke="currentColor"/><polyline fill="none" stroke="var(--accent)" strokeWidth="2" points={values.map((v,i)=>`${20+i*320/Math.max(1,values.length-1)},${95-v/max*75}`).join(' ')}/>{values.map((v,i)=><circle key={i} r="4" cx={20+i*320/Math.max(1,values.length-1)} cy={95-v/max*75} fill="var(--accent)"><title>Attempt {i+1}: {v}</title></circle>)}<text x="20" y="115">Earlier</text><text x="290" y="115">Latest</text></svg><p className="muted">{values.map((v,i)=>`${i+1}: ${v}`).join(' · ')}</p></figure>;
  }
  return <div className="reports-workspace"><div className="page-heading"><div><p className="eyebrow">Practice intelligence</p><h1>Your interview reports</h1><p className="intro">Review the evidence, choose one change, and try again.</p></div><button className="text-button" disabled={loading||busy} onClick={()=>setRetry(n=>n+1)}>Refresh reports</button></div>
    {loading&&<div className="report-skeleton" role="status">Loading private reports…</div>}
    {error&&<p className="error" role="alert">{error} <button className="text-button" onClick={()=>setRetry(n=>n+1)}>Retry reports</button></p>}
    {!loading&&!error&&!attempts.length&&<div className="list-empty"><h2>Your first report starts with one answer</h2><p>Open Question bank → Start Practice Drill → Start recording. Review the audio, then choose Analyze Response.</p></div>}
    {attempts.length>0&&<>
      <div className="report-score-grid"><div><strong>{total}</strong><span>Saved attempts</span></div><div><strong>{new Set(real.map(a=>a.question_id)).size}</strong><span>Questions practiced</span></div><div><strong>{avg('wpm')}</strong><span>Average WPM</span></div><div><strong>{avg('filler_rate')}</strong><span>Fillers / minute</span></div><div><strong>{real.length?seconds(real.reduce((n,a)=>n+a.duration,0)/real.length):"—"}</strong><span>Average duration</span></div></div>
      <p className="muted">{attempts.length} of {total} attempts loaded. Averages and patterns use loaded, completed, non-demo attempts. Scores describe this coaching rubric, not hiring readiness.</p>
      {next!==null&&<button className="text-button" disabled={busy} onClick={more}>Load older attempts</button>}
      {real.length>0&&<><div className="report-chart-grid">{chart('Overall','Coaching score')}{chart('wpm','WPM')}{chart('filler_rate','Fillers per minute')}</div>
        <h3>STAR balance across loaded attempts</h3><div className="star-balance">{STAR_KEYS.map(k=>{const n=real.reduce((sum,a)=>sum+a.metrics.star[k].percent,0)/real.length;return <div key={k}><span>{k} {n.toFixed(0)}%</span><meter min={0} max={100} value={n} aria-label={`${k} allocation`} /></div>;})}</div>
        <div className="report-columns"><section><h3>Delivery versus content</h3><svg viewBox="0 0 320 200" role="img" aria-label="Delivery on horizontal axis, mean structure, specificity, relevance and impact on vertical axis. Exact values follow."><line x1="40" y1="170" x2="300" y2="170" stroke="currentColor"/><line x1="40" y1="10" x2="40" y2="170" stroke="currentColor"/><text x="90" y="195">Delivery 0–100 →</text><text x="45" y="15">Content 0–100 ↑</text>{points.map((a,i)=>{const s=a.analysis.scores;const content=['Structure','Specificity','Relevance','Impact'].filter(k=>Number.isFinite(s[k]));const v=content.reduce((n,k)=>n+s[k],0)/content.length;return <circle key={a.id} cx={40+2.5*s.Delivery} cy={170-v*1.5} r="5" fill="var(--violet)"><title>{i+1}: delivery {s.Delivery}, content {v.toFixed(1)}</title></circle>;})}</svg><details><summary>Chart values</summary><ul>{points.map((a,i)=><li key={a.id}>Attempt {i+1}: {Object.entries(a.analysis.scores).map(([k,v])=>`${k} ${v}`).join(' · ')}</li>)}</ul></details></section>
        <section><h3>Competency practice coverage</h3><p className="muted">Coaching averages; not employability or readiness predictions. Fewer than three attempts is preliminary.</p>{[...new Set(real.map(a=>a.competency))].map(c=>{const g=real.filter(a=>a.competency===c);return <p key={c}>{c.replaceAll('_',' ')}: {g.length} attempts · mean score {(g.reduce((n,a)=>n+a.analysis.scores.Overall,0)/g.length).toFixed(0)}{g.length<3?" (preliminary)":""}</p>;})}</section></div></>}
      <h2>Pattern intelligence</h2>{insights.length?<ul className="coaching-list">{insights.map((p,i)=><li key={i}>{p.text}<div className="evidence-links">{p.ids.slice(0,5).map(id=><button className="text-button" key={id} onClick={()=>{setSelected(id);setCompare("");}}>Inspect {new Date(attempts.find(a=>a.id===id)!.created_at).toLocaleDateString()}</button>)}</div></li>)}</ul>:<p className="muted">Patterns require at least five real attempts across two questions using the same analysis version. Competency patterns require at least three matching attempts. No reliable pattern is available yet.</p>}
      <h2>Question history</h2>{groups.map(group=>{const complete=group.filter(a=>a.status==="completed"&&!a.is_mock);const best=complete.reduce<Attempt|null>((best,a)=>!best||a.analysis.scores.Overall>best.analysis.scores.Overall?a:best,null);return <details className="question-history" key={group[0].question_id}><summary>{group[0].prompt}<span className="muted">{group[0].competency.replaceAll('_',' ')} · {group.length} loaded attempts · latest {new Date(group[0].created_at).toLocaleString()} · best {best?.analysis.scores.Overall??"—"}</span></summary>{group.map(a=><div className="attempt-row" key={a.id}><button className="text-button" onClick={()=>{setSelected(a.id);setCompare("");}}>{new Date(a.created_at).toLocaleString()} · {a.status}{a.is_mock?" · demo":""}{a.status==="completed"?` · ${a.analysis.scores.Overall}/100 · ${a.metrics.wpm} WPM · ${a.metrics.filler_rate} fillers/min`:""}</button><button className="delete-button" disabled={busy} onClick={()=>remove(a)}>Delete attempt</button></div>)}</details>;})}
      {current&&<section className="selected-report"><h2>{current.prompt}</h2><p className="muted">{new Date(current.created_at).toLocaleString()} · {current.competency.replaceAll('_',' ')}</p><button className="delete-button" disabled={busy} onClick={()=>remove(current)}>Delete this attempt permanently</button>
        {current.status==="completed"&&<><label className="field">Compare with an earlier attempt<select className="qb-select" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Choose an attempt</option>{real.filter(a=>a.question_id===current.question_id&&a.created_at<current.created_at&&a.rubric_version===current.rubric_version&&a.pipeline_version===current.pipeline_version).map(a=><option key={a.id} value={a.id}>{new Date(a.created_at).toLocaleString()} · {a.analysis.scores.Overall}/100</option>)}</select></label>{previous&&<div className="mri-evidence"><h3>Attempt comparison</h3>{compareAttempts(previous,current).map(p=><p key={p}>{p}</p>)}<div className="star-balance">{STAR_KEYS.map(k=><p key={k}>{k}: {previous.metrics.star[k].percent}% → {current.metrics.star[k].percent}%</p>)}</div><details><summary>Earlier transcript evidence</summary><p>{previous.transcript}</p></details></div>}</>}
        <InterviewReport key={current.id} attempt={current}/></section>}
    </>}
  </div>;
}
