/* eslint-disable @typescript-eslint/no-require-imports -- Standalone Playwright browser regression suite. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');const os=require('node:os');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'mecode-practice-'));
const config=fs.readFileSync(path.resolve(__dirname,'../.env.local'),'utf8');
const projectUrl=config.match(/^NEXT_PUBLIC_SUPABASE_URL=(.+)$/m)?.[1].trim();
if(!projectUrl)throw new Error('Browser test requires the frontend public Supabase URL configuration. No real authentication or database writes are used.');
const ref=new URL(projectUrl).hostname.split('.')[0];
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['microphone']});
 const uid='a2b6c429-c6e8-4e6e-9d45-a3f77c253ca1',exp=Math.floor(Date.now()/1000)+3600;
 const user={id:uid,email:'practice-test@example.test',aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{},created_at:new Date().toISOString()};
 const token=[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:uid,exp,role:'authenticated'})).toString('base64url'),'test'].join('.');
 await context.addInitScript(({user,token,exp,ref})=>localStorage.setItem(`sb-${ref}-auth-token`,JSON.stringify({user,access_token:token,refresh_token:'test',expires_at:exp,expires_in:3600,token_type:'bearer'})),{user,token,exp,ref});
 await context.route(`${projectUrl}/**`,route=>route.fulfill({json:route.request().url().includes('/auth/')?user:[]}));
 let failList=true,failSubmit=true,recordedReport=null,seeded=null;
 await context.route('**/api/practice*',async route=>{
  const req=route.request();const url=new URL(req.url());
  if(req.method()==='GET'&&seeded&&url.searchParams.get('configuration')!=='1')return route.fulfill({json:{attempts:seeded,total:seeded.length,next:null}});
  if(req.method()==='GET'&&failList){return route.fulfill({status:503,json:{error:'Test reports temporarily unavailable'}});}
  if(req.method()==='POST'&&failSubmit){failSubmit=false;return route.fulfill({status:503,json:{error:'Transcription is not configured. Add DEEPGRAM_API_KEY to backend/.env. Your recording is preserved.'}});}
  const suffix=req.method()==='DELETE'?'/'+url.searchParams.get('id'):url.searchParams.get('configuration')==='1'?'/config':url.search;
  const response=await fetch('http://127.0.0.1:8001/api/practice'+suffix,{method:req.method(),headers:{Authorization:'Bearer browser-test','Content-Type':req.headers()['content-type']||'application/json','X-Practice-Meta':req.headers()['x-practice-meta']||''},body:req.method()==='POST'?req.postDataBuffer():undefined});
  const body=await response.text();
  if(req.method()==='POST'&&response.ok){for(const line of body.split('\n'))if(line.startsWith('data: ')){const e=JSON.parse(line.slice(6));if(e.type==='result')recordedReport=e.report;}}
  await route.fulfill({status:response.status,contentType:response.headers.get('content-type'),body});
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000');
 await page.getByRole('tab',{name:'Reports',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'Test reports temporarily unavailable'}).waitFor();
 failList=false; await page.getByRole('button',{name:'Retry reports',exact:true}).click();
 await page.getByRole('heading',{name:'Your first report starts with one answer'}).waitFor();
 await page.getByRole('tab',{name:'Question Bank (50)'}).click();
 await page.getByRole('button',{name:'Start Practice Drill',exact:false}).click();
 await page.getByRole('button',{name:'Start recording',exact:true}).click();
 await page.getByRole('button',{name:'Stop recording',exact:true}).waitFor();
 assert(await page.getByRole('tab',{name:'Reports',exact:true}).isDisabled());
 assert(await page.getByRole('button',{name:'Next Question',exact:false}).isDisabled());
 await page.screenshot({path:path.join(output,'recorder-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(output,'recorder-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.waitForTimeout(2500);
 await page.getByRole('button',{name:'Pause recording',exact:true}).click();
 await page.getByRole('button',{name:'Resume recording',exact:true}).click();
 await page.waitForTimeout(1500);
 await page.getByRole('button',{name:'Stop recording',exact:true}).click();
 await page.getByRole('button',{name:'Analyze Response',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'DEEPGRAM_API_KEY'}).waitFor();
 assert.equal(await page.locator('.practice-recorder>audio').count(),1);
 await page.getByRole('button',{name:'Analyze Response',exact:true}).click();
 await page.getByRole('button',{name:'Open saved Reports',exact:true}).waitFor({timeout:90000});
 await page.getByRole('button',{name:'Open saved Reports',exact:true}).click();
 assert.equal(await page.locator('#reports-panel .selected-report').count(),0);
 await page.locator('#reports-panel .question-history summary').first().click();
 await page.locator('#reports-panel .attempt-row .text-button').first().click();
 await page.getByRole('button',{name:'Close report',exact:true}).click();
 assert.equal(await page.locator('#reports-panel .selected-report').count(),0);
 await page.locator('#reports-panel .attempt-row .text-button').first().click();
 await page.locator('#reports-panel .response-disclosure>summary').click();
 await page.getByRole('heading',{name:'Answer breakdown',exact:true}).waitFor();
 assert.equal(await page.locator('#reports-panel .pace-chart').count(),0);

 await page.locator('#reports-panel .mri-segment').nth(2).click();
 assert.match(await page.locator('#reports-panel .mri-evidence').first().innerText(),/compared two options/);
 await page.screenshot({path:path.join(output,'reports-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(output,'reports-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile overflow');
 await page.reload();await page.getByRole('tab',{name:'Reports',exact:true}).click();
 assert.equal(await page.locator('#reports-panel .selected-report').count(),0);
 await page.locator('#reports-panel .question-history summary').first().click();
 await page.locator('#reports-panel .attempt-row .text-button').first().click();
 await page.getByRole('button',{name:'Close report',exact:true}).click();
 assert.equal(await page.locator('#reports-panel .selected-report').count(),0);
 await page.locator('#reports-panel .attempt-row .text-button').first().click();
 await page.locator('#reports-panel .response-disclosure>summary').click();
 await page.getByRole('heading',{name:'Answer breakdown',exact:true}).waitFor();
 assert.equal(await page.locator('#reports-panel .pace-chart').count(),0);

 page.on('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Delete this attempt permanently',exact:true}).click();
 await page.getByRole('heading',{name:'Your first report starts with one answer'}).waitFor();
 await page.getByRole('tab',{name:'Question Bank (50)'}).click();
 await page.getByRole('button',{name:'Start Practice Drill',exact:false}).click();
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});
 await page.getByRole('button',{name:'Start recording',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'Microphone access was denied'}).waitFor();
  assert(await page.getByRole('tab',{name:'Reports',exact:true}).isEnabled());
 seeded=Array.from({length:6},(_,i)=>{
  const a=structuredClone(recordedReport);a.id=`fixture-${i}`;a.question_id=i%2?'question-a':'question-b';a.is_mock=false;a.created_at=`2026-09-${20+i}T12:00:00Z`;a.duration=60+i*4;a.metrics.wpm=135+i*5;a.analysis.scores.Overall=50+i*5;a.analysis.scores.Specificity=40+i*4;a.metrics.star.result.percent=0;return a;
 }).reverse();
 await page.getByRole('tab',{name:'Reports',exact:true}).click();
 await page.getByRole('button',{name:'Refresh reports',exact:true}).click();

 await page.getByRole('heading',{name:'Competency practice coverage'}).waitFor();
 await page.locator('#reports-panel .question-history summary').first().click();
 await page.locator('#reports-panel .attempt-row .text-button').first().click();
 assert.match(await page.locator('#reports-panel').innerText(),/Preliminary trend/);
 await page.getByLabel('Compare with an earlier attempt').selectOption('fixture-3');
 await page.getByRole('heading',{name:'Attempt comparison',exact:true}).waitFor();
 await page.screenshot({path:path.join(output,'progress-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:path.join(output,'progress-desktop.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Browser tests passed: reports failure/retry/empty, recording/pause/replay, navigation protection, missing-key retry, streamed report, evidence selection, desktop/mobile, reload, permanent delete, denied microphone.');
 console.log('Browser inspection images:',output);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
